



var Qlist_0_00 = [
    "甘草芭樂",
    "咖哩飯",
    "蜘蛛人",
    "咖啡牛奶",
    "香蒜麵包",
    "法式吐司",
    "人生勝利組",
    "任意門",
    "隱型斗篷",
    "健達出奇蛋",
    "一見鍾情",
    "番茄",
    "胡椒餅",
    "抹茶巧克力",
    "薄荷巧克力",
    "龍舌蘭",
    "菜雞",
    "泡牛奶",
    "烤餅乾",
    "簽字筆",
    "下午茶",
    "漢堡肉",
    "豪大大雞排",
];

var Qlist_0_film_afi = [
    "公民凱恩<span>Citizen Kane, 1941</span>",
    "教父<span>The Godfather, 1972</span>",
    "卡薩布蘭卡<span>Casablanca, 1942</span>",
    "亂世佳人<span>Gone with the Wind, 1939</span>",
    "阿拉伯的勞倫斯<span>Lawrence of Arabia, 1962</span>",
    "綠野仙蹤<span>The Wizard of Oz, 1939</span>",
    "畢業生<span>The Graduate, 1967</span>",
    "碼頭風雲<span>On the Waterfront, 1954</span>",
    "辛德勒的名單<span>Schindler's List, 1993</span>",
    "雨中曲<span>Singin' in the Rain, 1952</span>",
    "生活多美好<span>It's a Wonderful Life, 1946</span>",
    "日落大道<span>Sunset Boulevard, 1950</span>",
    "桂河大橋<span>The Bridge on the River Kwai, 1957</span>",
    "熱情似火<span>Some Like It Hot, 1959</span>",
    "星球大戰<span>Star Wars, 1977</span>",
    "彗星美人<span>All About Eve, 1950</span>",
    "非洲女王號<span>The African Queen, 1951</span>",
    "驚魂記<span>Psycho, 1960</span>",
    "唐人街<span>Chinatown, 1974</span>",
    "飛越瘋人院<span>One Flew Over the Cuckoo's Nest, 1975</span>",
    "憤怒的葡萄<span>The Grapes of Wrath, 1940</span>",
    "2001太空漫遊<span>2001: A Space Odyssey, 1968</span>",
    "馬耳他之鷹<span>The Maltese Falcon, 1941</span>",
    "憤怒的公牛<span>Raging Bull, 1980</span>",
    "外星人E.T.<span>E.T. THE EXTRA-TERRESTRIAL, 1982</span>",
    "奇愛博士<span>Dr. Strangelove, 1964</span>",
    "雌雄大盜<span>Bonnie and Clyde, 1967</span>",
    "現代啓示錄<span>Apocalypse Now, 1979</span>",
    "史密斯先生到華盛頓<span>Mr. Smith Goes to Washington, 1939</span>",
    "浴血金沙<span>The Treasure of the Sierra Madre, 1948</span>",
    "安妮·霍爾<span>Annie Hall, 1977</span>",
    "教父2<span>The Godfather Part II, 1974</span>",
    "正午<span>High Noon, 1952</span>",
    "殺死一隻知更鳥<span>To Kill a Mockingbird, 1962</span>",
    "一夜風流<span>It Happened One Night, 1934</span>",
    "午夜牛郎<span>Midnight Cowboy, 1969</span>",
    "黃金時代<span>The Best Years of Our Lives, 1946</span>",
    "雙重賠償<span>Double Indemnity, 1944</span>",
    "日瓦戈醫生<span>Doctor Zhivago, 1965</span>",
    "西北偏北<span>North by Northwest, 1959</span>",
    "西區故事<span>West Side Story, 1961</span>",
    "後窗<span>Rear Window, 1954</span>",
    "金剛<span>King Kong, 1933</span>",
    "一個國家的誕生<span>The Birth of a Nation, 1915</span>",
    "慾望號街車<span>A Streetcar Named Desire, 1951</span>",
    "發條橙<span>A Clockwork Orange, 1971</span>",
    "出租車司機<span>Taxi Driver, 1976</span>",
    "大白鯊<span>Jaws, 1975</span>",
    "白雪公主和七個小矮人<span>Snow White and the Seven Dwarfs, 1937</span>",
    "虎豹小霸王<span>Butch Cassidy and the Sundance Kid, 1969</span>",
    "費城故事<span>The Philadelphia Story, 1940</span>",
    "亂世忠魂<span>From Here to Eternity, 1953</span>",
    "莫扎特傳<span>Amadeus, 1984</span>",
    "西線無戰事<span>All Quiet on the Western Front, 1930</span>",
    "音樂之聲<span>The Sound of Music, 1965</span>",
    "陸軍野戰醫院<span>M*A*S*H, 1970</span>",
    "第三人<span>The Third Man, 1949</span>",
    "幻想曲<span>Fantasia, 1940</span>",
    "無因的反叛<span>Raiders of the Lost Ark, 1955</span>",
    "奪寶奇兵<span>Rebel Without a Cause, 1981</span>",
    "迷魂記<span>Vertigo, 1958</span>",
    "窈窕淑男<span>Tootsie, 1982</span>",
    "關山飛渡<span>Stagecoach, 1939</span>",
    "第三類接觸<span>Close Encounters of the Third Kind, 1977</span>",
    "沉默的羔羊<span>The Silence of the Lambs, 1991</span>",
    "電視台風雲<span>Network, 1976</span>",
    "諜網迷魂<span>The Manchurian Candidate, 1962</span>",
    "一個美國人在巴黎<span>An American in Paris, 1951</span>",
    "原野奇俠<span>Shane, 1953</span>",
    "法國販毒網<span>The French Connection, 1971</span>",
    "阿甘正傳<span>Forrest Gump, 1994</span>",
    "賓虛<span>Ben-Hur, 1959</span>",
    "呼嘯山莊<span>Wuthering Heights, 1939</span>",
    "淘金記<span>The Gold Rush, 1925</span>",
    "與狼共舞<span>Dances with Wolves, 1990</span>",
    "城市之光<span>City Lights, 1931</span>",
    "美國風情畫<span>American Graffiti, 1973</span>",
    "洛奇<span>Rocky, 1976</span>",
    "獵鹿人<span>The Deer Hunter, 1978</span>",
    "日落黃沙<span>The Wild Bunch, 1973</span>",
    "摩登時代<span>Modern Times, 1936</span>",
    "巨人傳<span>Giant, 1956</span>",
    "野戰排<span>Platoon, 1986</span>",
    "冰血暴<span>Fargo, 1996</span>",
    "鴨羹<span>Duck Soup, 1933</span>",
    "叛艦喋血記<span>Mutiny on the Bounty, 1935</span>",
    "科學怪人<span>Frankenstein, 1931</span>",
    "逍遙騎士<span>Easy Rider, 1969</span>",
    "巴頓將軍<span>Patton, 1970</span>",
    "爵士歌王<span>The Jazz Singer, 1927</span>",
    "窈窕淑女<span>My Fair Lady, 1964</span>",
    "郎心如鐵<span>A Place in the Sun, 1951</span>",
    "桃色公寓<span>The Apartment, 1960</span>",
    "好傢伙<span>Goodfellas, 1990</span>",
    "低俗小説<span>Pulp Fiction, 1994</span>",
    "搜索者<span>The Searchers, 1956</span>",
    "育嬰奇譚<span>Bringing Up Baby, 1938</span>",
    "不可饒恕<span>Unforgiven, 1992</span>",
    "猜猜誰來吃晚餐<span>Guess Who's Coming to Dinner, 1967</span>",
    "勝利之歌<span>Yankee Doodle Dandy, 1942</span>",
];

var Qlist_0_tw_food = [
    "滷肉飯<span>Braised pork rice  </span>",
    "牛肉麵<span>Beef noodles   </span>",
    "蚵仔煎<span>Oyster omelet   </span>",
    "珍珠奶茶<span>Bubble tea   </span>",
    "虱目魚<span>Milkfish    </span>",
    "擔仔麵<span>Slack Season danzai noodles </span>",
    "生煎包<span>Pan-fried buns   </span>",
    "割包、刈包<span>Gua bao   </span>",
    "鐵蛋Iron<span>egg    </span>",
    "鳳梨酥<span>Pineapple cake   </span>",
    "甜不辣<span> Tian bu la (Taiwanese</span>",
    "肉圓<span>Ba wan (Giant meat dumplings)</span>",
    "炸雞<span>Fried chicken   </span>",
    "蔥抓餅Flaky<span>scallion pancakes   </span>",
    "蚵仔麵線<span>Oyster vermicelli   </span>",
    "臭豆腐<span>Stinky tofu   </span>",
    "油豆腐<span>Oily bean curd  </span>",
    "豆干<span>Dried tofu   </span>",
    "蕃薯<span>Sweet potato   </span>",
    "剉冰<span>Shaved ice mountain  </span>",
    "胡椒餅<span>Pepper cakes   </span>",
    "小籠包<span>Dumplings    </span>",
    "魚丸湯<span>Fish ball soup  </span>",
    "藥燉排骨<span>Ribs stewed in medicinal herbs</span>",
    "鵝肉<span> Goose   </span>",
    "鼎邊銼<span> Ding bian cuo </span>",
    "麻糬<span>Mochi    </span>",
    "加熱滷味<span>Anything braised with Lantern soy</span>",
    "筒仔米糕<span>Tube rice pudding  </span>",
    "台式早餐（豆漿油條）<span>Taiwanesebreakfast</span>",
    "豬血湯<span>Pig’s blood rice pudding </span>",
    "三杯雞<span>Three-cup chicken   </span>",
    "粄條<span>Ban tiao noodles  </span>",
    "洪瑞珍三明治<span>Horng Ryen Jen Sandwich </span>",
    "愛玉<span>Aiyu jelly   </span>",
    "皮蛋豆腐<span>Pidan tofu   </span>",
    "潤餅<span>Taiwan burrito   </span>",
    "麻辣火鍋<span>Spicy hotpot   </span>",
    "雞翅飯捲<span>Chicken wing rice roll </span>",
    "貢丸湯<span>Pork balls soup  </span>",
    "便當<span>Biandang    </span>",
    "大腸包小腸<span>Doubled layer roll (sausage) </span>",
    "肉粽<span>    </span>",
    "肉羹麵<span>    </span>",
    "車輪餅<span>    </span>",
    "草仔粿<span>    </span>",
    "碗粿<span>Salty rice pudding  </span>",
    "豬血糕<span>Pigs blood cake  </span>",
    "雞排<span>    </span>",
    "竹筒飯<span>Tube-shaped container rice  </span>",
    "發粿<span>Rice cake   </span>",
    "芒果冰<span>Mango milk shaved ice </span>",
    "燒仙草<span>Boiled Grass Jelly  </span>",
    "綠豆湯<span>mung bean  soup </span>",
    "紅豆湯<span>red bean soup  </span>",
    "酸梅湯<span>sour prune juice  </span>",
    "芋圓<span>taro balls   </span>",
    "豆花<span>tofu pudding   </span>",
    "粉圓冰<span>powder circle ice  </span>",
    "客家擂茶<span>Hakka Lei tea  </span>",
    "木瓜牛奶<span> papaya smoothie  </span>",
    "米漿<span>peanut rice milk  </span>",
    "鍋貼<span>pot stickers   </span>",
    "蘿蔔糕<span>radish cake   </span>",
    "水餃<span>dumpling    </span>",
    "蒸餃<span>Steamed dumplings   </span>",
    "炒米粉<span>Fried rice noodles  </span>",
    "魷魚羹<span>Squid Potage   </span>",
    "油飯<span>Glutinous oil rice  </span>",
    "蔥油餅<span>Flaky scallion pancakes  </span>",
    "蛋花湯<span>egg drop soup  </span>",
    "花生湯<span>peanut soup   </span>",
    "米粉湯<span>Rice Noodle Soup  </span>",
    "餛飩湯<span>wonton soup   </span>",
    "當歸羊肉<span>    </span>",
    "卜肉<span>    </span>",
    "黑胡椒鐵板麵<span>    </span>",
    "麻辣鴨血臭豆腐<span>    </span>",
    "煎餃<span>    </span>",
    "飯糰<span>Rice roll   </span>",
    "炒麵<span>    </span>",
    "餛飩麵<span>Wonton & noodles  </span>",
    "刀削麵<span>Sliced noodles   </span>",
    "麻醬麵<span>Sesame paste noodles  </span>",
    "鴨肉麵<span>Duck with noodles  </span>",
    "鵝肉麵<span>Goose with noodles  </span>",
    "榨菜肉絲麵<span>Pork, pickled mustard green noodles</span>",
    "鍋燒意麵<span>    </span>",
    "鹹粥<span>    </span>",
    "肉燥飯<span>    </span>",
    "鹹酥雞<span>    </span>",
    "炒泡麵<span>    </span>",
    "四神湯<span>    </span>",
    "阿給<span>    </span>",
    "蛋炒飯<span>    </span>",
    "蚵嗲<span>    </span>",
    "鹹水雞<span>    </span>",
    "炸鮮奶<span>    </span>",
    "炸熱狗<span>    </span>",
    "牛舌餅<span>    </span>",
    "羊肉爐<span>    </span>",
    "豬腳<span>    </span>",
    "泡泡冰<span>Shaved ice   </span>",
    "綿綿冰<span>Mein mein ice  </span>",
    "客家小炒<span>    </span>",
    "火雞肉飯<span>    </span>",
    "花生糖<span>    </span>",
    "剝皮辣椒<span>    </span>",
    "蜜餞<span>    </span>",
    "拔絲地瓜<span>    </span>",
    "虱目魚粥<span>    </span>",
    "古早味蛋餅<span>    </span>",
    "涼麵<span>    </span>",
    "麵線糊<span>    </span>",
    "台南蝦仁飯<span>    </span>",
    "台式可麗餅<span>    </span>",
    "櫻花蝦米糕<span>    </span>",
    "古早味蛋糕<span>    </span>",
    "地瓜球<span>    </span>",
    "黑白切<span>    </span>",
    "米苔目<span>    </span>",
    "肉包<span>    </span>",
    "白糖粿<span>    </span>",
    "芋粿巧<span>    </span>",
    "小捲米粉<span>    </span>",
    "台式馬卡龍<span>    </span>",
    "土魠魚羹<span>    </span>",
    "豬油拌飯<span>    </span>",
    "珍珠奶茶<span>    </span>",
    "棺材板<span>Coffin bread   </span>",
    "鱔魚麵<span>Eel noodles   </span>",
    "蔥抓餅<span>    </span>",
    "烤魷魚<span>    </span>",
    "烤玉米<span>    </span>",
    "雞蛋糕<span>    </span>",
    "天婦羅<span>Tempura    </span>",
    "蝦球<span>Shrimp balls   </span>",
    "春捲<span>Spring rolls   </span>",
    "雞捲<span>Chicken rolls   </span>",
    "烤香腸<span>    </span>",
    "冰火湯圓<span>    </span>",
    "甘蔗汁<span>Sugar cane juice  </span>",
    "酸梅汁<span>Plum juice   </span>",
    "楊桃汁<span>Star fruit juice  </span>",
    "青草茶<span>Herb juice   </span>",
    "皮蛋<span>100-year egg   </span>",
    "鐵蛋<span>1000-year egg   </span>",
    "茶葉蛋<span>Tea egg   </span>",
    "滷蛋<span>Hard boiled egg  </span>",
    "鹹鴨蛋<span>Salted duck egg  </span>",
    "燒餅<span>Clay oven rolls  </span>",
    "油條<span>Fried bread stick  </span>",
    "韭菜盒<span>Fried leek dumplings  </span>",
    "饅頭<span>Steamed buns   </span>",
    "糖葫蘆<span>Tomatoes on sticks  </span>",
    "壽桃<span>Longevity Peaches   </span>",
    "芝麻球<span>Glutinous rice sesame balls </span>",
    "麻花<span>Fried dough twist  </span>",
    "雙胞胎<span>Horse hooves   </span>",
];


var Qlist_0_jpdrama = [
    "仁醫",
    "機器女友Q10",
    "告白",
    "MR.Brain腦科學先生",
    "咩妹的完美執事",
    "篤姬",
    "BLOODY MONDAY",
    "Last Friends",
    "流星之絆",
    "戀空",
    "求婚大作戰",
    "魚干女又怎樣",
    "花樣少年少女",
    "貧窮貴公子",
    "空中急診英雄",
    "死亡筆記本",
    "14歲小媽媽",
    "交響情人夢",
    "我的老大，我的英雄",
    "女王的教室",
    "流星花園",
    "改造野豬妹",
    "東大特訓班",
    "一公升的眼淚",
    "Orange Days",
    "白色巨塔",
    "夏之雪",
    "池袋西口公園",
    "大和拜金女",
    "To Heart至死不渝的愛",
    "魔女的條件",
    "孩子們的戰爭",
    "長假",
    "惡作劇之吻",
    "情書",
    "無家可歸的小孩",
    "東京愛情故事",
];
var Qlist_0_aten = [
    "CIC ROOM",
    "KVM Switch",
    "PDU",
    "VK2100",
    "Power Distribution & Rack Solutions",
    "Professional Audio/Video",
    "Control System",
    "4-Port Serial Expansion Box",
    "Seamless Switch",
    "Presentation switch",
    "Video matrix switch",
    "Room Booking System",
    "DisplayPort HDBaseT-Lite Receiver",
    "HDMI over IP ",
    "4K",
];



var Qlist_0_tw_town = [
    "連江縣北竿鄉",
    "連江縣南竿鄉",
    "連江縣東引鄉",
    "連江縣莒光鄉",
    "金門縣烈嶼鄉",
    "金門縣金城鎮",
    "金門縣金寧鄉",
    "金門縣金沙鎮",
    "金門縣金湖鎮",
    "金門縣烏坵鄉",
    "高雄市六龜區",
    "高雄市永安區",
    "臺南市北門區",
    "臺南市將軍區",
    "臺南市七股區",
    "高雄市小港區",
    "高雄市前鎮區",
    "高雄市苓雅區",
    "高雄市旗津區",
    "高雄市林園區",
    "高雄市前金區",
    "高雄市新興區",
    "高雄市鳳山區",
    "高雄市大寮區",
    "高雄市鼓山區",
    "高雄市三民區",
    "高雄市鳥松區",
    "高雄市左營區",
    "高雄市仁武區",
    "高雄市楠梓區",
    "高雄市大社區",
    "高雄市梓官區",
    "高雄市大樹區",
    "高雄市橋頭區",
    "高雄市彌陀區",
    "高雄市燕巢區",
    "高雄市岡山區",
    "高雄市路竹區",
    "高雄市阿蓮區",
    "高雄市茄萣區",
    "高雄市湖內區",
    "高雄市田寮區",
    "高雄市旗山區",
    "高雄市美濃區",
    "臺南市南區",
    "臺南市仁德區",
    "臺南市中西區",
    "高雄市茂林區",
    "臺南市東區",
    "臺南市安平區",
    "臺南市龍崎區",
    "臺南市關廟區",
    "臺南市歸仁區",
    "臺南市北區",
    "高雄市內門區",
    "高雄市杉林區",
    "臺南市永康區",
    "臺南市新化區",
    "臺南市左鎮區",
    "臺南市安南區",
    "臺南市新市區",
    "臺南市安定區",
    "臺南市山上區",
    "臺南市西港區",
    "臺南市善化區",
    "臺南市玉井區",
    "臺南市大內區",
    "高雄市甲仙區",
    "臺南市佳里區",
    "臺南市官田區",
    "臺南市麻豆區",
    "臺南市楠西區",
    "臺南市南化區",
    "臺南市六甲區",
    "臺南市下營區",
    "臺南市學甲區",
    "臺南市柳營區",
    "臺南市東山區",
    "臺南市新營區",
    "臺南市鹽水區",
    "高雄市那瑪夏區",
    "臺南市後壁區",
    "臺南市白河區",
    "臺東縣長濱鄉",
    "臺東縣東河鄉",
    "臺東縣成功鎮",
    "臺東縣大武鄉",
    "臺東縣達仁鄉",
    "臺東縣金峰鄉",
    "臺東縣太麻里鄉",
    "臺東縣臺東市",
    "臺東縣卑南鄉",
    "臺東縣延平鄉",
    "臺東縣鹿野鄉",
    "臺東縣關山鎮",
    "臺東縣池上鄉",
    "臺東縣海端鄉",
    "屏東縣牡丹鄉",
    "屏東縣佳冬鄉",
    "屏東縣枋寮鄉",
    "嘉義縣東石鄉",
    "嘉義縣布袋鎮",
    "雲林縣臺西鄉",
    "雲林縣麥寮鄉",
    "屏東縣恆春鎮",
    "屏東縣車城鄉",
    "屏東縣滿州鄉",
    "屏東縣枋山鄉",
    "屏東縣獅子鄉",
    "屏東縣林邊鄉",
    "屏東縣春日鄉",
    "屏東縣東港鎮",
    "屏東縣南州鄉",
    "屏東縣新埤鄉",
    "屏東縣崁頂鄉",
    "屏東縣新園鄉",
    "屏東縣潮州鎮",
    "屏東縣來義鄉",
    "屏東縣萬丹鄉",
    "屏東縣竹田鄉",
    "屏東縣萬巒鄉",
    "屏東縣泰武鄉",
    "屏東縣麟洛鄉",
    "屏東縣內埔鄉",
    "屏東縣屏東市",
    "屏東縣瑪家鄉",
    "屏東縣長治鄉",
    "屏東縣九如鄉",
    "屏東縣鹽埔鄉",
    "屏東縣里港鄉",
    "屏東縣霧臺鄉",
    "屏東縣三地門鄉",
    "屏東縣高樹鄉",
    "嘉義縣大埔鄉",
    "嘉義縣義竹鄉",
    "嘉義縣鹿草鄉",
    "嘉義縣中埔鄉",
    "嘉義縣水上鄉",
    "嘉義縣朴子市",
    "嘉義縣番路鄉",
    "嘉義縣竹崎鄉",
    "嘉義縣六腳鄉",
    "嘉義縣民雄鄉",
    "嘉義縣新港鄉",
    "嘉義縣梅山鄉",
    "嘉義縣阿里山鄉",
    "嘉義縣溪口鄉",
    "雲林縣水林鄉",
    "雲林縣北港鎮",
    "嘉義縣大林鎮",
    "雲林縣口湖鄉",
    "雲林縣大埤鄉",
    "雲林縣元長鄉",
    "雲林縣古坑鄉",
    "雲林縣四湖鄉",
    "雲林縣斗南鎮",
    "雲林縣東勢鄉",
    "雲林縣褒忠鄉",
    "雲林縣虎尾鎮",
    "雲林縣土庫鎮",
    "雲林縣斗六市",
    "雲林縣林內鄉",
    "雲林縣西螺鎮",
    "雲林縣崙背鄉",
    "雲林縣二崙鄉",
    "屏東縣琉球鄉",
    "高雄市鹽埕區",
    "雲林縣莿桐鄉",
    "新北市中和區",
    "臺北市文山區",
    "桃園市新屋區",
    "新北市樹林區",
    "新北市永和區",
    "新北市深坑區",
    "桃園市中壢區",
    "桃園市桃園區",
    "新北市板橋區",
    "新北市石碇區",
    "臺北市大安區",
    "臺北市萬華區",
    "臺北市中正區",
    "臺北市信義區",
    "臺北市南港區",
    "桃園市龜山區",
    "新北市新莊區",
    "新北市泰山區",
    "臺北市松山區",
    "新北市平溪區",
    "臺北市大同區",
    "桃園市觀音區",
    "臺北市中山區",
    "新北市三重區",
    "新北市雙溪區",
    "新北市蘆洲區",
    "基隆市暖暖區",
    "臺北市內湖區",
    "桃園市蘆竹區",
    "桃園市大園區",
    "新北市貢寮區",
    "新北市五股區",
    "基隆市仁愛區",
    "新北市林口區",
    "新北市瑞芳區",
    "新北市汐止區",
    "基隆市信義區",
    "基隆市七堵區",
    "基隆市中山區",
    "新北市八里區",
    "基隆市安樂區",
    "臺北市士林區",
    "臺北市北投區",
    "新北市萬里區",
    "新北市淡水區",
    "新北市金山區",
    "新北市三芝區",
    "新北市石門區",
    "南投縣魚池鄉",
    "南投縣鹿谷鄉",
    "花蓮縣豐濱鄉",
    "花蓮縣富里鄉",
    "花蓮縣玉里鎮",
    "花蓮縣瑞穗鄉",
    "花蓮縣卓溪鄉",
    "花蓮縣光復鄉",
    "花蓮縣鳳林鎮",
    "花蓮縣萬榮鄉",
    "花蓮縣壽豐鄉",
    "花蓮縣吉安鄉",
    "花蓮縣花蓮市",
    "花蓮縣新城鄉",
    "花蓮縣秀林鄉",
    "宜蘭縣蘇澳鎮",
    "宜蘭縣南澳鄉",
    "宜蘭縣冬山鄉",
    "宜蘭縣羅東鎮",
    "宜蘭縣三星鄉",
    "宜蘭縣五結鄉",
    "宜蘭縣大同鄉",
    "宜蘭縣宜蘭市",
    "宜蘭縣員山鄉",
    "宜蘭縣壯圍鄉",
    "宜蘭縣礁溪鄉",
    "臺中市南區",
    "南投縣竹山鎮",
    "彰化縣二水鄉",
    "南投縣集集鎮",
    "南投縣信義鄉",
    "彰化縣溪州鄉",
    "南投縣名間鄉",
    "彰化縣竹塘鄉",
    "彰化縣北斗鎮",
    "彰化縣田中鎮",
    "彰化縣大城鄉",
    "南投縣水里鄉",
    "彰化縣田尾鄉",
    "彰化縣埤頭鄉",
    "彰化縣社頭鄉",
    "彰化縣永靖鄉",
    "南投縣南投市",
    "南投縣中寮鄉",
    "彰化縣埔心鄉",
    "彰化縣溪湖鎮",
    "彰化縣員林市",
    "彰化縣二林鎮",
    "彰化縣大村鄉",
    "南投縣草屯鎮",
    "彰化縣埔鹽鄉",
    "彰化縣芳苑鄉",
    "彰化縣芬園鄉",
    "南投縣埔里鎮",
    "彰化縣花壇鄉",
    "彰化縣福興鄉",
    "彰化縣秀水鄉",
    "臺中市霧峰區",
    "彰化縣彰化市",
    "臺中市大里區",
    "彰化縣鹿港鎮",
    "南投縣國姓鄉",
    "臺中市烏日區",
    "臺中市中區",
    "彰化縣線西鄉",
    "彰化縣和美鎮",
    "臺中市西區",
    "臺中市太平區",
    "臺中市南屯區",
    "臺中市北區",
    "臺中市大肚區",
    "彰化縣伸港鄉",
    "臺中市西屯區",
    "臺中市北屯區",
    "臺中市潭子區",
    "南投縣仁愛鄉",
    "臺中市大雅區",
    "臺中市沙鹿區",
    "臺中市新社區",
    "臺中市豐原區",
    "臺中市石岡區",
    "臺中市龍井區",
    "臺中市神岡區",
    "臺中市東勢區",
    "臺中市清水區",
    "臺中市后里區",
    "臺中市外埔區",
    "苗栗縣卓蘭鎮",
    "臺中市大安區",
    "苗栗縣三義鄉",
    "臺中市大甲區",
    "臺中市和平區",
    "苗栗縣大湖鄉",
    "苗栗縣苑裡鎮",
    "苗栗縣泰安鄉",
    "苗栗縣銅鑼鄉",
    "苗栗縣公館鄉",
    "苗栗縣通霄鎮",
    "苗栗縣西湖鄉",
    "苗栗縣苗栗市",
    "苗栗縣獅潭鄉",
    "苗栗縣頭屋鄉",
    "苗栗縣南庄鄉",
    "苗栗縣造橋鄉",
    "苗栗縣後龍鎮",
    "新竹縣五峰鄉",
    "苗栗縣三灣鄉",
    "苗栗縣頭份市",
    "新竹縣峨眉鄉",
    "新竹縣北埔鄉",
    "苗栗縣竹南鎮",
    "新竹縣橫山鄉",
    "新竹縣尖石鄉",
    "新竹縣寶山鄉",
    "新竹縣竹東鎮",
    "新竹縣芎林鄉",
    "新竹市東區",
    "新竹市香山區",
    "新竹縣關西鎮",
    "桃園市復興區",
    "新竹市北區",
    "新竹縣竹北市",
    "新竹縣新埔鎮",
    "桃園市龍潭區",
    "新北市烏來區",
    "桃園市大溪區",
    "新竹縣湖口鄉",
    "新竹縣新豐鄉",
    "新北市三峽區",
    "桃園市楊梅區",
    "桃園市平鎮區",
    "新北市鶯歌區",
    "新北市坪林區",
    "桃園市八德區",
    "新北市新店區",
    "新北市土城區",
    "基隆市中正區",
    "宜蘭縣頭城鎮",
    "臺東縣綠島鄉",
    "臺東縣蘭嶼鄉",
    "高雄市桃源區",
    "澎湖縣七美鄉",
    "澎湖縣白沙鄉",
    "澎湖縣西嶼鄉",
    "澎湖縣馬公市",
    "澎湖縣望安鄉",
    "澎湖縣湖西鄉",
    "嘉義縣太保市",
    "臺中市東區",
    "臺中市梧棲區",
    "嘉義市西區",
    "嘉義市東區",
];




var Qlist_0_file_2000 = [
    "黑金企業<span>There Will Be Blood，2007</span>",
    "自由之心<span>12 Years a Slave，2013</span>",
    "年少時代<span>Boyhood，2014</span>",
    "肌膚之侵<span>Under the Skin，2013</span>",
    "花樣年華<span>In the Mood for Love，2000</span>",
    "隱藏攝影機<span>Hidden，2005</span>",
    "紐約浮世繪<span>Synecdoche, New York，2008</span>",
    "月光下的藍色男孩<span>Moonlight，2016</span>",
    "薩瑪的漫長等待<span>Zama，2017</span>",
    "美國賤隊：世界警察<span>Team America: World Police，2004</span>",
    "穆荷蘭大道<span>Mulholland Drive，2001</span>",
    "索爾之子<span>Son of Saul，2015</span>",
    "遠離天堂<span>Far From Heaven，2002</span>",
    "白鬼子<span>White Material，2009</span>",
    "小偷家族<span>Shoplifters，2018</span>",
    "殺人一舉<span>The Act of Killing，2012</span>",
    "絕美之城<span>The Great Beauty，2013</span>",
    "正經好人<span>A Serious Man，2009</span>",
    "林肯<span>Lincoln，2012</span>",
    "羅馬<span>Roma，2018</span>",
    "白色緞帶<span>The White Ribbon，2009</span>",
    "神隱少女<span>Spirited Away，2001</span>",
    "芭樂特：哈薩克青年必修（理）美國文化<span>Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan，2006</span>",
    "依達的抉擇<span>Ida，2013</span>",
    "逃出絕命鎮<span>Get Out，2017</span>",
    "一一<span>A One and a Two，2000</span>",
    "歡迎來到布達佩斯大飯店<span>The Grand Budapest Hotel，2014</span>",
    "永生樹<span>The Tree of Life，2011</span>",
    "內布拉斯加<span>Nebraska，2013</span>",
    "纏繞之蛇<span>Leviathan，2014</span>",
    "安諾瑪麗莎<span>Anomalisa，2015</span>",
    "地心引力<span>Gravity，2013</span>",
    "天才一族<span>The Royal Tenenbaums，2001</span>",
    "孩子<span>The Child，2002</span>",
    "45年<span>45 Years，2015</span>",
    "分居風暴<span>A Separation，2011</span>",
    "厄夜變奏曲<span>Dogville，2003</span>",
    "安納托利亞故事<span>Once Upon a Time in Anatolia，2011</span>",
    "米克的近路<span>Meek’s Cutoff，2010</span>",
    "Unrelated<span>，2007</span>",
    "下女的誘惑<span>The Handmaiden，2016</span>",
    "4月3週又2天<span>4 Months, 3 Weeks and 2 Days，2007</span>",
    "華爾街之狼<span>The Wolf of Wall Street，2013</span>",
    "巔父人生<span>Toni Erdmann，2016</span>",
    "憲法第十三條修正案<span>13th，2016</span>",
    "玩美女人<span>Volver，2006</span>",
    "Margaret<span>，2011</span>",
    "歡樂之家<span>The House of Mirth，2000</span>",
    "24小時狂歡派對<span>24 Hour Party People，2002</span>",
    "愛在日落巴黎時<span>Before Sunset，2004</span>",
    "臥虎藏龍<span>Crouching Tiger, Hidden Dragon，2000</span>",
    "愛是一條狗<span>Amores Perros，2000</span>",
    "海上焰火<span>Fire at Sea，2016</span>",
    "社群網戰<span>The Social Network，2010</span>",
    "創世紀<span>Russian Ark，2002</span>",
    "熾愛琴人<span>Behind the Candelabra，2013</span>",
    "荒野之心<span>Leave No Trace，2018</span>",
    "咆哮山莊<span>Wuthering Heights，2011</span>",
    "Gangs of Wasseypur<span>，2012</span>",
    "熊麻吉<span>Ted，2012</span>",
    "紀念我們的相愛時光<span>The Souvenir，2019</span>",
    "等待幸福<span>Waiting for Happiness，2002</span>",
    "凱文怎麼了<span>We Need to Talk about Kevin，2011</span>",
    "超人特攻隊<span>The Incredibles，2004</span>",
    "幸福的拉札洛<span>Happy as Lazzaro，2018</span>",
    "斷背山<span>Brokeback Mountain，2005</span>",
    "非普通教慾<span>Dogtooth，2009</span>",
    "畫世紀：透納先生<span>Mr. Turner，2014</span>",
    "柏靈頓熊熊出任務<span>Paddington 2，2017</span>",
    "銀幕大角頭<span>Anchorman: The Legend of Ron Burgundy，2004</span>",
    "我想有個家<span>Capernaum，2018</span>",
    "與巴席爾跳華爾滋<span>Waltz with Bashir，2008</span>",
    "蘇珊夫人尋婚計<span>Love & Friendship，2016</span>",
    "大獄言家<span>A Prophet，2009</span>",
    "遲來的守護者<span>Philomena，2013</span>",
    "十段生命的律動<span>Ten，2002</span>",
    "愛情，不用翻譯<span>Lost in Translation，2003</span>",
    "瞞天過海<span>Ocean’s Eleven，2001</span>",
    "茉莉人生<span>Persepolis，2007</span>",
    "噩夢輓歌<span>Requiem for a Dream，2000</span>",
    "發現心節奏<span>Fish Tank，2009</span>",
    "莎拉波莉家庭詩篇<span>Stories We Tell，2012</span>",
    "人間有情天<span>The Son’s Room，2001</span>",
    "熱帶幻夢<span>Tropical Malady，2005</span>",
    "燃燒烈愛<span>Burning，2018</span>",
    "險路勿近<span>No Country for Old Men，2007</span>",
    "吹動大麥的風<span>The Wind that Shakes the Barley，2006</span>",
    "娥摩拉罪惡之城<span>Gomorrah，2008</span>",
    "刺蝟少年<span>The Selfish Giant，2013</span>",
    "巴黎電幻世代<span>Eden，2014</span>",
    "山村猶有讀書聲<span>Etre et Avoir，2002</span>",
    "危機倒數<span>The Hurt Locker，2008</span>",
    "啊！人生<span>You, the Living，2007</span>",
    "神鬼戰士<span>Gladiator，2000</span>",
    "以你的名字呼喚我<span>Call Me By Your Name，2017</span>",
    "非孕私生活<span>Private Life，2018</span>",
    "華氏911<span>Fahrenheit 9/11，2004</span>",
    "黑暗騎士<span>The Dark Knight，2008</span>",
    "璀璨情詩<span>Bright Star，2009</span>",
    "從前，有個好萊塢<span>Once Upon a Time in Hollywood，2019</span>",
];






var Qlist_0_chuka = [
    "萬里長城",
    "小當家",
    "精靈姊姊",
    "阿貝師傅",
    "菊下樓",
    "李提督",
    "LTD",
    "紹安",
    "0皿X",
    "黃金炒飯",
    "國營餐館",
    "魔幻麻婆豆腐",
    "辣香色燙麻",
    "四川料理的仙女",
    "特級廚師",
    "陽泉酒家",
    "十全大師",
    "嘟嘟",
    "炒青江菜",
    "阿Ｑ",
    "王福",
    "青椒肉絲",
    "龍鎮酒家",
    "月暈",
    "廣州餃子大賽",
    "鳳凰翡翠餃子",
    "餃子兄弟",
    "阿魯",
    "武雄",
    "及第師傅",
    "冕頂餃子",
    "廣廚聯",
    "火焰餃子",
    "朗文大師",
    "你的問題不是廚藝，而是你的人格有問題",
    "內個",
    "巨龍餃子",
    "昇龍餃子",
    "東江館小韓",
    "魔女芝琳",
    "伴林酒家小單",
    "阿飛",
    "蘭飛鴻",
    "國士無雙麵",
    "王虎",
    "龍鬚麵",
    "鹼水",
    "鬥味場",
    "雷花",
    "麵非麵",
    "鯰魚麵",
    "貓耳朵",
    "平淡的創意卻企圖以華麗的表演來掩飾，你應該感到慚愧。貧乏的想像力和技巧的沈迷，都是廚師的致命傷。小單，你做的料理的確沒有評分的必要。",
    "四郎",
    "鮑大人",
    "曲青村",
    "顏麗",
    "賈雄",
    "神秘的鍋巴料理",
    "連總督",
    "料理是帶給人們幸福的東西",
    "奇顏",
    "銀河麵",
    "伊格爾",
    "蕾雅",
    "招來不幸的雞",
    "雞窩鎮",
    "黑羽樓",
    "炒什錦蔬菜",
    "解師傅",
    "鋼棍",
    "擊墜記號",
    "黃金比例燒賣",
    "宇宙大燒賣",
    "牛魔刀",
    "李嚴",
    "吿別演唱會",
    "蠔油炒鴿肉",
    "海鐘公園前的異人館",
    "赤蛙肉",
    "梅香",
    "龍蝦三爭霸",
    "炸鳳尾蝦",
    "所以我說那個醬汁呢",
    "沒完成的料理根本沒有必要試吃",
    "吃吃看啊，你吃一口就知道了",
    "砂鍋料理",
    "乾貨",
    "黑暗料理界",
    "媽媽的味道",
    "寶山飛龍鍋",
    "你怎麼帥成這樣",
    "雷恩",
    "0勝恩",
    "猛牛青龍斬",
    "傳說中的廚具",
    "神前刀工對決",
    "七星刀",
    "大仙寺",
    "鯛魚",
    "七星瞬斷刀舞",
    "百穴菜刀",
    "鋼絲菜刀",
    "真鯛大陸圖",
    "北辰天狼刃",
    "羅漢水晶斬",
    "烈冰鮮鯛山",
    "轉生春捲",
    "永靈刀",
    "霸龍紋",
    "你還是21小時之後再來吧",
    "許林",
    "上海蟹",
    "龍鎮酒家",
    "黑雲旗",
    "樓麟艦",
    "錦毛虎駱可",
    "特級麵點師",
    "羅漢虎爪拔",
    "宴席料理對決",
    "頂湯",
    "彈跳甲魚湯",
    "煮凝結",
    "鹽漬梅",
    "難吃印",
    "白羅家",
    "麵點王羅根",
    "鎮魂麵",
    "白羅蛇轉練",
    "蜀漢老麵",
    "四神海鮮八寶包子",
    "黃金開口笑",
    "一丈青向恩",
    "七星破軍生墨魚片",
    "七星破軍迅切開",
    "羅歇",
    "蟹斗",
    "蟹肉蛋",
    "舌頭味覺疲勞招",
    "LED",
    "黑暗健身房",
    "595no拋瓦",
    "君さえいれば",
    "豆腐三重奏",
    "大魔術熊貓麻婆",
    "單林",
    "轉龍壺",
    "羅緬大人",
    "變色龍小麵碗塔",
    "魔聖銅器",
    "聲譽",
    "九華山",
    "御前料理對決",
    "麟廚師",
    "螳螂鬼揚士",
    "雙尾蠍賴賀",
    "滿漢全席",
    "新中華",
    "鳳凰水晶",
    "龍總管"
];



var Qlist_0_play20220902 = [
    "游泳圈",
    "紅綠燈",
    "行人道",
    "圓山飯店",
    "孟婆湯",
    "電線桿",
    "宏正自動科技",
    "女兒牆",
    "大師兄",
    "小護士",
    "救生員",
    "比基尼",
    "白色襯衫",
    "大西瓜",
    "沙灘排球",
    "綠油精",
    "摩天輪",
    "蹺蹺板",
    "鬼娃恰吉",
    "寶可夢",
    "護唇膏",
    "精華液",
    "小熊維尼",
    "割韭菜",
    "熱炒店",
    "馬來貘",
    "溜溜球",
    "熱氣球",
    "颱風天",
    "登山襪",
    "玉米濃湯",
    "蛋炒飯",
    "龜背芋",
    "彈簧床",
    "雲霄飛車",
    "頂天立地",
    "花園夜市"
];






var Qlist_1_01 = [
    "如果看到金城武熟睡在自己面前，你會做什麼?",
    "你最近都聽什麼歌?",
    "當你不知道要穿什麼顏色的衣服時，你會選什麼顏色?",
    "去年你最後悔的一件事是什麼?",
    "哪天你變身蜘蛛人，第一件事會做什麼?",
    "你昨天吃什麼當晚餐?",
    "你曾遇過最感動的事情是什麼?",
    "如果你有一張單程機票，你會去哪?",
    "你覺得人生勝利組是要具備什麼條件?",
    "如果你有任意門，你想去哪?",
    "如果你有隱型斗篷，你會怎麼做?",
    "如果你想重來，你會回到哪個時期?",
    "你相信一見鍾情嗎?",
    "你相信男女間有純友誼嗎?",
    "要對10年後的自己說一句話，你會說什麼?",
    "要對18歲的自己說一句話，你會說什麼?",
    "你最討厭的動物是什麼?",
    "你在Uber上發現沒帶錢包也沒帶手機，怎麼辦?",
    "如果你中10萬塊樂透，你要幹嘛?",
    "最近買過最貴的物品是什麼?",
    "上一次去台北101，是跟誰去?",
    "若發生地震你要逃跑只能拿一樣東西，你會拿什麼?",
    "你認為在哪跨年最浪漫?",
    "要選另一半，眼睛是要深遂的好．還是小眼睛好?",
    "愛情跟麵包，你會選哪一個?",
    "你醒來發現旁邊睡了一個陌生人，你會怎麼辦?",
    "如果你會功夫，你想要什麼功夫?",
    "提到劉德華，你會馬上想到什麼?",
    "最經典的西洋電影，你會推薦哪一部?",
    "你最喜歡和哪一個星座的人當朋友?",
    "當老闆對你說你明天可以不要來了，你會怎麼反應?",
    "最近一次去的遊樂園是哪一個?",
    "如果要跟一個人說對不起，你想對誰說?",
    "四個季節你最喜歡哪一個?",
    "提到NBA，你會想到哪個球星?",
    "要選台灣離島深度旅行，你會選哪裡?",
    "露營帳篷和露營車，你會選哪個住?",
    "夜釣小管和夜遊看梅花鹿，你會選哪個?",
    "當你另一半必須要有的一個特點?",
    "最喜歡的便利商店飲料?",
    "上廁所上到一半，老闆打來你會怎麼辦?",
    "最喜歡的夜市小吃?",
    "最近聽到的笑話?",
    "最喜歡的一句話(至理名言)?",
    "如果有下輩子，想當男生還是女生?",
    "回憶國小時期，現在還有印象的事是什麼?",
    "宏正上班第一天，最有印象的事?",
    "最喜歡的卡通人物?",
    "做過最有勇氣的事?",
    "扶老太太過馬路和淨灘，哪一件事你覺得比較有意義?",
    "聽到哪一句話，你會馬上翻臉?",
    "當你不爽的時候，會怎麼樣?",
    "看農民曆你會先看什麼資訊?",
    "你喜歡過聖誕節還是中秋節?",
    "你喜歡戴墨鏡還是戴帽子?",
    "彩虹七個顏色，你會喜歡哪一色?",
    "海水浴場和動物園，你比較喜歡哪一個?",
    "如果可以改變，你想多高(身高)?",
    "你退休後會想在哪個城市居住?",
    "珍珠和椰果，你比較喜歡飲料加哪種料?",
    "最推薦的飲料店?",
    "此時此刻你最想做的事是什麼?",
    "林志玲和侯佩岑，你覺得誰比較是你的菜?",
    "給你抱怨公司一件事，你會講什麼?",
    "當你和老闆獨處在電梯，從1樓搭到14樓的期間，你會講什麼話?",
    "近期發生你最後悔的事?",
];

var Qlist_1_cora = [
    "現場有幾個人戴眼鏡？",
    "Alex的中文全名是什麼？",
    "本中心第一高是誰？",
    "Ashley最喜歡的國家是哪？",
    "阿飛有幾個小孩？",
    "Alex和Anita在一起多久？",
    "你覺得Suzuki模仿誰最像？",
    "New的口頭禪",
    "Suzuki二女兒的小名是什麼？",
    "Wei現在搭什麼交通工具來上班？",
    "阿爆號稱是汐止XX?",
    "請說出現場每個人在宏正的麻吉是誰？",
    "New什麼顏色衣服最多？",
    "Wei是西元幾年出生的？",
    "上一次New請喝飲料是請哪一家？",
    "如果要比賽游泳，你覺得在場誰游最快？",
    "你還記得書磊身高幾公分嗎？",
    "你第一次吃到阿飛的下午茶是什麼？",
    "目前為止你最喜歡的合作對象是誰？",
    "目前為止你最討厭的合作對象是誰？",
    "會讓New暴怒的一句話是什麼？",
    "你覺得Alex生氣時會有什麼表現？",
    "Wei最喜歡的飲料是什麼口味？",
    "你覺得現在Ashley聽到什麼話會很開心？",
    "請你用一個形容詞形容Suzuki",
    "請馬上說出一個阿飛的優點",
    "在場誰曾經做過讓你佩服的事？是什麼事？",
    "你對書磊的第一印象是什麼？",
    "如果要對五年後的自己說句話，你會說什麼？",
    "你從祖國回來，生活最大的改變是什麼？",
    "玩具總動員-胡迪的經典台詞是什麼？",
    "你最喜歡的顏色是什麼？",
];







var Qlist_1_ch = [
    "小當家從小是在什麼地方長大？<span>-樓麟艦- -異人館- -陽泉酒家- -菊下樓-</span>",
    "下列哪一道料理，「不是」小當家的作品？<span>-大魔術熊貓麻婆豆腐- -鳳凰水晶- -真鯛大陸圖- -火焰餃子-</span>",
    "下列哪一個不是傳說的廚具？<span>-迦樓羅刀- -轉龍壺- -北辰天狼刃- -魔聖銅器-</span>",
    "在台灣動畫版的《中華一番》中，下列何者對戰紀錄是0勝<span>-向恩- -小當家- -阿Q- -雷恩-</span>",
    "請問下列那一到料理，少了「那個醬汁」？<span>-火焰餃子- -閘蟹斗- -炸鳳尾蝦- -豆腐三重奏-</span>",
    "下列哪一道作品，「不」符合「國士無雙」的元素？<span>-八寶麵- -超濃縮湯頭麵- -東坡肉麵- -超細龍鬚麵-</span>",
    "在特級廚師測驗中，下列哪一道作品，因「創意不足」，遭到淘汰<span>-貓耳麵- -鯰魚麵- -野味麵- -炒蛋花餡牛肉麵-</span>",
    "請問「麵點王」羅根所持有的特殊食材是？<span>-東吳老麵- -春秋老麵- -蜀漢老麵- -天寶老麵-</span>",
    "請問在樓麟艦篇當中，向恩的作品是？<span>-黃金炒飯- -豆腐三重奏- -蟹肉蛋- -魚翅香腸-</span>",
    "請問，在台灣版動畫《中華一番》當中，唯一勝過小當家的廚師是？<span>-阿飛- -十全大師- -紹安- -王福-</span>",
];



var Qlist_1_ch_a = [4, 4, 3, 4, 4, 3, 3, 1, 3, 3, 4]












// 此 List 名稱需與上方實際名稱一致
var Qlist_0s = [
    Qlist_0_00,
    Qlist_0_film_afi,
    Qlist_0_file_2000,
    Qlist_0_tw_food,
    Qlist_0_tw_town,
    Qlist_0_jpdrama,
    Qlist_0_chuka,
    Qlist_0_aten,
    Qlist_0_play20220902
]
var Qlist_0s_Name = [
    "default",
    "Film AFI",
    "Film 2000",
    "Taiwan Food",
    "Taiwan Town",
    "JP Drama",
    "ちゅうかいちばん！",
    "ATENer",
    "送舊迎新"
]





var Qlist_1s = [
    Qlist_1_01,
    Qlist_1_cora,
    Qlist_1_ch
]

var Qlist_1s_Name = [
    "default",
    "Cora",
    "中華一番"
]
